### ISSUE TITLE
Restrict twig version

### ISSUE THREAD

**Issue by simonkey** [Bartacus/BartacusTwigBundle#3]
The newest twig versions `1.41.0` and `2.10.0` don't render anything if there is an error or `die()` is called.

The following commit introduced this problem:
https://github.com/twigphp/Twig/pull/2995

Solution: restrict the twig versions to the previous ones: `1.40.1` / `2.9.0` until a better fix is found

**Comment by QuingKhaos** [comment]
released as 1.0.3
